const data = {
  products: [
    {
      _id: '1',
      name: 'Cobra kai ultimo confronto',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Camiseta 100% algodão estampa em Silk Screen. Tecida inteiramente com fios de algodão, oferece um toque agradável e conforto por permitir a troca de calor. O fio cardado possui fibras mais curtas, Retém mais suor e é mais fresca em dias quentes. ',
    },
    {
      _id: '2',
      name: 'Dragon ball z ',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 20,
      description:
        '100% algodãoDimensões:P: Altura: 72cm   Largura: 50cmM: Altura: 75cm   Largura: 52cmG: Altura: 78cm   Largura: 54cmGG: Altura: 79cm  Largura: 56cm...',
    },
    {
      _id: '3',
      name: ' Naruto Sakura Girl Casual',
      category: 'Shirts',
      image: '/images/p3.jpg',
      countInStock: 2,
      price: 220,
      brand:
        'Novas mulheres da moda / homens 3D Print Naruto Sakura Girl Casual T-shirts',
      rating: 4.8,
      numReviews: 23,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 50,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 80,
      description: 'high quality product',
    },
  ],
};
export default data;
